### ISSUE TITLE
Mildly faulty coveragepy detection

### ISSUE THREAD

**Issue by akx** [codecov/codecov-bash#116]
Hey,

Looks like codecov-bash 8b76995 doesn't want to upload Python coverage unless the `coverage` executable is around.  This detection is a little faulty when using a tox-based build, since `coverage` will likely be installed within the tox-managed virtualenv. 

The obvious workaround is to install `coverage` in the outside-of-tox environment. Maybe one could use `-f .coverage` to force codecov-bash to upload that file, too?

The particular build I'm seeing this with is this: https://github.com/valohai/valohai-cli/blob/d548951eeee90ffaadc675c27e0f7a8bc637951d/circle.yml – see below for the Codecov output.

```
==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    + /tmp/circle-artifacts.r6wumes
    + /tmp/circle-junit.lsxnAtl
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```

Seems that this has been broken for us since (approximately) 13 Apr 2017 (https://github.com/valohai/valohai-cli/pull/16 is the last PR to have Codecov reports in this particular project). Not sure how I hadn't noticed the conspicuous lack of coverage reports though... 😅

**Comment by stevepeak** [comment]
Hi @akx, Indeed there are some gotchas to this. Tox and virtualenvs are tricky to work with.

The `.coverage` files are "locked" in the venv therefore we suggest running coverage from inside your tox env.  https://github.com/codecov/codecov-python#using-tox

It is not clear to me of any way around this.... Using `-f .coverage` will not solve the issue because the `.coverage` files does not have all the context needed to build a real coverage report.

> Closing issue because it's repository specific and solution is outlined here: https://github.com/codecov/codecov-python#using-tox

Thanks!
