### ISSUE TITLE
new codecov.io/bash script broke my coverage on travis-CI

### ISSUE THREAD

**Issue by samwalls** [codecov/codecov-bash#162]
I've spent much of today upgrading and re-downgrading my compiler versions, test runners, gcov, etc. as my coverage suddenly went from 75% to 44%. First I thought it might have been some issue with my codebase, however I don't think this is the case.

I went into travis, and restarted an old build - this means the build was on the same commit for my project, same travis script etc.. The only possible differences between the builds are: packages available to travis at runtime, and the codecov.io bash script. The old build, from about a month ago, had proper coverage data.

In the restarted build I observed lots of 0% line coverage, and even "no executable lines" from the gcov output which codecov.io's script runs. Whereas on previous builds, it's clear that gcov is producing sensible line coverage numbers.

The version of the codecov script which worked was `0b37652`, and the current version which I'm observing the undesirable behaviour is `8a28df4`. This all seems odd as the former version (which I can only assume refers to a commit hash) is from a year ago, and I can't seem to find the latter.

To be even more sure, I specifically downloaded the file on [this commit](https://raw.githubusercontent.com/codecov/codecov-bash/0b376529f626b50b7d4a9fb734e0e50d28b9b91e/codecov), used it in my travis script, and found it to fix my coverage.

I don't know what has changed under the hood, perhaps something irreversible, but if not I think this should be looked into.

The project in question is a C++17 project built with cmake, make, GCC-7, gtest 1.7.0, gcov-7 (incidentally I found the same behaviour on gcc-8, gtest 1.8.2, and gcov-8).

**Comment by a2wagner** [comment]
I can confirm this issue. I spent much time on figuring out why the Travis build of a project suddenly failed when running the coverage part. The build was cancelled because the log limit was exceeded, the codecov script produced way more output than before stating "no executable lines".

After some time of comparisons and triggering old builds which started to fail as well, I noticed the version hash had changed like described in the previous comment. Using the script from commit `0b37652` fixed the problem for me as well.

The project in question is written in C++11 and built with cmake, GCC-4.9.2 as well as GCC-8.2.0.

**Comment by davidbeckingsale** [comment]
I think the change is caused by https://github.com/codecov/codecov-bash/commit/1ac948214de2ebf4b9a5a764bf428f932457f296. Looking at the diff, it seems like the switch from to `execdir` is the culprit.

You can see this comparing `0b37652` and master: https://github.com/codecov/codecov-bash/compare/0b37652...master

I'm also observing this problem in multiple projects that use C++11, CMake and GCC.

**Comment by roystgnr** [comment]
This appears to be the same bug that hit us a while ago at https://github.com/libqueso/queso/pull/665 - thanks to @davidbeckingsale for the workaround at https://github.com/LLNL/RAJA/pull/611; hopefully that'll work for me too.

**Comment by donmccaughey** [comment]
This bit me as well recently. I picked up a personal project this week that I last touched in October 2018. Spent an evening tearing my hair out trying to figure out what broke.  Thanks @samwalls, @a2wagner, @davidbeckingsale and @roystgnr for the confirmation and work-around.

The magic fix for me was to change

    bash <(curl -s https://codecov.io/bash)

to

    bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/8b76995ad4a95a61cecd4b049a448a402d91d197/codecov)

in order to use [commit 8b76995](https://github.com/codecov/codecov-bash/commit/8b76995ad4a95a61cecd4b049a448a402d91d197) of the uploader script (dated 8-Feb-2018).  As of today, this is only four commits behind `HEAD`, and those commits all look like minor additions to the script.

**Comment by zbeekman** [comment]
ping @stevepeak
