### ISSUE TITLE
Support AppVeyor

### ISSUE THREAD

**Issue by jayvdb** [codecov/codecov-bash#56]
Appveyor has bash installed and in the path, and it should work.

As a short term measure, it should raise an error immediately on Appveyor, informing the user that it does not work on Appveyor.

**Comment by felixfbecker** [comment]
I am using the bash uploader successfully in multiple projects:

https://github.com/felixfbecker/vscode-php-debug/blob/2afa122eb27f1dcbd20d8657c0d78ad0aed0ff50/appveyor.yml#L24-L29

https://github.com/sourcegraph/javascript-typescript-langserver/blob/a34ac0bde47e7219481e2d20bc8b3b5ea816dddc/appveyor.yml#L22-L27

https://github.com/sequelize/sequelize/blob/3f5927f5bb47db85f5e0401d5a876f652fef1cd3/appveyor.yml#L35-L41

MinGW Unix tools just have to be added to PATH so that `find` uses the Unix util and not the DOS command.

Imo this solution is better than requiring installation with Python.

**Comment by jayvdb** [comment]
So `bash` is in the `PATH`, but that is not sufficient because `find` needs to be added to the front of the `PATH`?

The bash script should be able to detect AppVeyor and amend the `PATH` for its own process only.

Then AppVeyor can be 'supported' in https://github.com/codecov/codecov-bash#ci-providers

**Comment by felixfbecker** [comment]
Uhm, I don't know if `bash` is in the PATH by default, but all the unix tools (including bash) that CodeCov uses are ported to Windows in MSYS which is available on AppVeyor in `C:\msys64`.

**Comment by jayvdb** [comment]
https://github.com/codecov/codecov-bash/pull/138 helps with this

**Comment by drazisil** [comment]
There are a couple open issues and PRs, but Appveyor does work. Closing this issue in favor of those.
