### ISSUE TITLE
codecov-bash not working when using Jenkins pipeline

### ISSUE THREAD

**Issue by bonigarcia** [codecov/codecov-bash#93]
Hi there,

I am not able to update the codecov coverage report using the bash script in a Jenkins pipeline. After executing my tests, I call the codecov-bash script as follows:

`sh "curl -s https://codecov.io/bash | bash -s - -t ${TORM_CODECOV_TOKEN} || echo 'Codecov did not collect coverage reports'"`

In the Jenkins console we can check that the bash script failed:

```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-d109cc7


[0;90m==>[0m Jenkins CI detected.
Codecov did not collect coverage reports
```
Looking for some similar open issues, I found this #68. It seems that the problem is related with the way in which environment variables such as `GIT_COMMIT` and `GIT_BRANCH` are read. I tried to solve it changing my Jenkinsfile as follows, but still no luck:

```
def codecovArgs = '-K '
if (env.GITHUB_PR_NUMBER != '') {
    codecovArgs += "-B ${env.GITHUB_PR_TARGET_BRANCH} " +
        "-C ${env.GITHUB_PR_HEAD_SHA} " +
        "-P ${env.GITHUB_PR_NUMBER} "
} else {
    codecovArgs += "-B ${env.GIT_BRANCH} " +
        "-C ${env.GIT_COMMIT} "
}
sh "curl -s https://codecov.io/bash | bash -s - ${codecovArgs} -t ${TORM_CODECOV_TOKEN} || echo 'Codecov did not collect coverage reports'"
```

Any idea? Thanks in advance.

**Comment by richistron** [comment]
same here

**Comment by apanzerj** [comment]
ditto

**Comment by aliriorivera** [comment]
Hi, I had the same problem and after several tries, I realize what was the problem and how to fix it 

the problem is that when Bash tries to know what was the last sha commit (env.GIT_COMMIT), it is getting a void value. For that reason there is going to be a 502 error: missing required fields (in Jenkins logs when trying to upload the report). To fix it, try to run "git rev-parse HEAD" and store the result in a variable (let's say **resultFromGit**) before you run codecov. At the end, you just need to add the parameter as: 

` curl -s codecovaddress | bash -s - -C ${resultFromGit} -t yourCodecovToken`

that was what worked for me to fix that error!!!

**Comment by drazisil** [comment]
Closing stale issue, I'm not aware if this still being an problem.
